const loginFields = [
  {
    labelText: "Email address",
    labelFor: "email-address",
    id: "email_address",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Email address",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
  },
];

const signupFields = [
  {
    labelText: "First Name",
    labelFor: "first-name",
    id: "fname",
    name: "fname",
    type: "text",
    autoComplete: "fname",
    isRequired: true,
    placeholder: "First Name",
  },
  {
    labelText: "Last Name",
    labelFor: "last-name",
    id: "lname",
    name: "lname",
    type: "text",
    autoComplete: "lname",
    isRequired: true,
    placeholder: "Last Name",
  },
  {
    labelText: "Spire ID",
    labelFor: "spire-id",
    id: "sid",
    name: "spire-id",
    type: "spire-id",
    autoComplete: "spire-id",
    isRequired: true,
    placeholder: "SPIRE ID",
  },
  {
    labelText: "Email address",
    labelFor: "email-address",
    id: "email_address",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Email address",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
  },
  {
    labelText: "Confirm Password",
    labelFor: "confirm-password",
    id: "confirm-password",
    name: "confirm-password",
    type: "password",
    autoComplete: "confirm-password",
    isRequired: true,
    placeholder: "Confirm Password",
  },
];

export { loginFields, signupFields };
